CREATE VIEW V_YJ_Stock
AS
SELECT FMASTERID,FSTOCKID,FNUMBER,FUseOrgId,FDOCUMENTSTATUS,FFORBIDSTATUS
	  ,FCREATORID,FCREATEDATE,FMODIFIERID,FMODIFYDATE
  FROM T_BD_STOCK WHERE FDOCUMENTSTATUS = 'C' AND FFORBIDSTATUS = 'A'

